id: 1                        # 服务器ID
name: 'game-1'               # 服务器名
externalIp: '10.51.28.97'    # 外网IP
tcpPort: 8888                # 对外端口
innerPort: 9527              # RPC端口
webPort: 10086               # 后台端口

game:
  local: 'F:\slg_demo_design\server' #策划数据路径
  debug: true                #调试模式
  saveInterval: 300          #存档时间间隔(单位:秒)
  offlineInterval: 3600      #离线玩家在内存中的存活时间(单位:秒)
  maxConcurrentUser: 10000   #单区最高在线人数
  maxRegisterUser: 100000    #单区最大注册人数

protocol:
  heartBeat: 120 # 网关心跳检测时间(0 不进行心跳检测)
  compress: false #网关数据包压缩
  compressThreshold: 512 #压缩阀值
  crypto: false # 网关数据包加密

db:
  jdbcUrl: 'jdbc:mysql://1.15.9.113:3306/game?autoReconnect=true&useUnicode=true&characterEncoding=utf-8'
  jdbcUser: 'root'           #数据库用户名
  jdbcPassword: 'yaO!*Ym54M*XZ1yy'  #数据库密码

cache:
  -
    type: 1              #global库
    ip: '1.15.9.113'
    port: 6789
    index: 0
    password: 'VZ#hKuR%i3fTNh&9'

  -
    type: 2              #local库
    ip: '1.15.9.113'
    port: 6790
    index: 0
    password: 'VZ#hKuR%i3fTNh&9'
rpc:
  timeout: 5000            # RPC超时时间